# Définitions des cibles
README.md: guessinggame.sh
	echo "# Project Guessing Game" > README.md
	echo "File generated with makefile" >> README.md
	echo "" >> README.md
	echo "Date: $$(date)" >> README.md
	echo "" >> README.md
	echo "Number of line in guessinggame.sh : $$(wc -l < guessinggame.sh)" >> README.md

clean:
	rm -f README.md
